extends Node

signal player_hp_changed
signal player_shield_hp_changed
signal mothership_hp_changed
signal mothership_shield_hp_changed
signal dead_ship
signal ship_hurt

signal game_ready
signal convoy_reached_wormhole
signal player_reached_wormhole
signal game_over
signal restart
signal mothership_advance

signal selected_ship_changed

signal opening_ship_upgrades
signal closing_ship_upgrades
